### ISSUE TITLE
在 vite 中使用 tenon-maker 加载组件时样式异常

### ISSUE THREAD

**Issue by panmenglin** [panmenglin/tenon#2]
vite 的热更新机制会更改 css 文件内容，导致 shadowdom 的样式异常

![image](https://user-images.githubusercontent.com/12044749/148925191-f7a88eac-c2a6-4632-be16-763e910d1830.png)

**Comment by marrviin** [comment]
该问题可以在组件打包时给 css 文件名增加后缀 `?direct`  即可
vite 机制中会判断 css 文件名，匹配 `/(\?|&)direct\b/` 则会直接返回 css 文件内容
